create table Users(
    id bigint not null auto_increment,
    first_name varchar(200),
    last_name varchar(200),
    nationality varchar(200),
    date_of_birth varchar(200),
    `language` varchar(200),
    phone varchar(200),
    `country of residence` varchar(200),
    sex varchar(200),
    `marital status` varchar(200),
    occupation varchar(200),
    `visa type` varchar(200),
    `status` varchar(200),
    `percentage` int,
    `passport number` varchar(200),
    `issue date` varchar(200),
    `passport url` varchar(200),
    `country of issue` varchar(200),
    `expiry date` varchar(200),
    `country of choice` varchar(200),
    `application id` varchar(200),
    `document url` varchar(200),
    `service agent` varchar(200),
    primary key (id)
);